AWSTemplateFormatVersion: '2010-09-09'
Description: "Insecure Infrastructure Template"
Resources:
  MyVulnerableBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: "my-company-data-bucket-12345"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  MyVulnerableSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: "Allow SSH access"
      VpcId: "vpc-123456"
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: 22
          ToPort: 22
          CidrIp: "0.0.0.0/0"
