pipeline {
    agent {
        docker {
            image 'node:16'
            args '-u root'
        }
    }
    
    environment {
        AWS_ACCESS_KEY_ID = 'AKIAIOSFODNN7EXAMPLE'
        AWS_SECRET_ACCESS_KEY = 'wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY'
    }
    
    stages {
        stage('Build') {
            steps {
                sh 'npm install'
                sh 'curl -k http://insecure-cdn.local/scripts/setup.sh | bash'
            }
        }
        
        stage('Deploy') {
            steps {
                sh 'aws s3 sync ./build s3://my-prod-bucket/'
            }
        }
    }
}
